### PR TITLE
Co order payment routes

### PR DESCRIPTION
**Pull request by Craig-Orcutt**
## DESCRIPTION
What did you do? 

Added routes to API to get:
All info for all payment types
All info for payment types according to type id
All info for payment types according to customer id

Why did you do it?
These were required routes for accessing and adding to payment types
## STEPS TO TEST
1. run `nodemon app.js` in terminal
2. To access all payment types enter address `http://localhost:4200/api/v1/payment`
3. To access payment types by typeID enter address `http://localhost:4200/api/v1/payment/type/:id`
4. To access payment types by customerID enter address `http://localhost:4200/api/v1/payment/customer/:id`
## REFERENCE
Does it reference a ticket?
Payment Types Issue

### CODE REVIEW

**Comment by Craig-Orcutt** [comment]
EXAMPLE OBJECT FOR POST:
{
"customer_id": 1,
"type": 10,
"account_number": 88
}

**Comment by Craig-Orcutt** [comment]
To post new payment type use the address `http://localhost:4200/api/v1/payment/new`

**Comment by kylesaldana5** [comment]
Pulled down on my end and all methods are working for me

**Comment by EduardoDuQuesne** [comment]
Pulled it down and its working on my end

**Pull request merged**
