### PR TITLE
finished Display Customers that haven't placed an Order

### PR DESCRIPTION
**Pull request by kylesaldana5**
## DESCRIPTION
What did you do? 
Created a route for seeing all customers who haven't placed an order 

Why did you do it?
It is a requirement of the project
## STEPS TO TEST
1. Rebuild the data base if necessary
2. Run nodemon app.js
3. Test functionality
	* http://localhost:4200/api/v1//customers/?active=false

## REFERENCE
Does it reference a ticket?
Yes Display Customers that haven't placed an Order

### CODE REVIEW

**Comment by ben-marcantel** [comment]
looks like active 1 and 0 are coming back

**Comment by kylesaldana5** [comment]
Thanks for fixing looks good 👍

**Comment by gmarkay** [comment]
I made some changes, should run smoothly now.

**Comment by Craig-Orcutt** [comment]
Looks great. Thanks for fixing that bug.

**Comment by ben-marcantel** [comment]
working now

**Pull request merged**
